### ISSUE TITLE
Список стеков

### ISSUE THREAD

**Issue by efureev** [tarampampam/docker-compose-deployer#21]
https://github.com/tarampampam/docker-compose-deployer/blame/master/docs/v1-client-side-cli.md#L48

Выводим последний поднятый стек?
Где храним список стеков?

**Comment by tarampampam** [comment]
Смотри описание команды:

https://github.com/tarampampam/docker-compose-deployer/blame/master/docs/v1-client-side-cli.md#L388

Клиент нигде не хранит список стеков, а берет его с сервера
