### ISSUE TITLE
Не вижу в доступных флагах - timeout

### ISSUE THREAD

**Issue by efureev** [tarampampam/docker-compose-deployer#25]
https://github.com/tarampampam/docker-compose-deployer/blame/master/docs/v1-client-side-cli.md#L298

https://github.com/tarampampam/docker-compose-deployer/blame/master/docs/v1-client-side-cli.md#L320

**Comment by tarampampam** [comment]
Этот "флаг" передается в параметрах для исполнения `docker-compose`, это не таймаут выполнения запроса к серверу.

Если считаешь нужным реализовать таймаут выполнения запроса к серверу, то, пожалуйста, создай PR с его описанием

**Comment by efureev** [comment]
Добавь в доку и закрывай
